# first step is to name our workflow by passing in the name field

name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
      # We can bring the MONGODB URL HERE TO CONNECT TO THE DB IN MONGO
        MONGO_URL: mongodb://localhost/nasa  # When this database nasa doesn't exist, one will be creates for us  to use
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # We can here specify the version of MongoDB to avoid the breack changes that may happen
        mongodb-version: ['4.4']


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js version 20
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          # node-version: "20"
          node-version: ${{ matrix.node-version }}
          # Setting up the MongoDb that will be created fresh for our CI and after our tests it is removed.
          # There is an action for that just like the above actions to checkout our codes

          # Let's first name it
      - name: Use MongoDB from github Actions
        uses: supercharge/mongodb-github-action@1.11.0 # used the uses to specify the name of the action
        with: 
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
